---
name: 'Lua Testing'
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: 'Testing'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v1'
        with:
          fetch-depth: 1
      - name: 'Install LuaRocks'
        run: 'apt install luarocks'
      - name: 'Install LuaCheck'
        run: 'luarocks install --local luacheck'
      - name: 'Run LuaCheck'
        run: '${HOME}/.luarocks/bin/luacheck . --no-color -q'
