---
name: 'CI'
on:
  push:
    branches:
      - 'master'

jobs:
  luacheck:
    name: 'Luacheck'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v1'
        with:
          fetch-depth: 1
      - name: 'Install LuaRocks'
        run: |
          sudo apt install luarocks
      - name: 'Install Luacheck'
        run: |
          luarocks install --local luacheck
      - name: 'Run Luacheck'
        run: |
          ${HOME}/.luarocks/bin/luacheck .
  release:
    name: 'Release Addon'
    runs-on: 'ubuntu-latest'
    needs: 'luacheck'
    steps:
      - uses: 'actions/checkout@v1'
        with:
          fetch-depth: 1
      - name: 'Download Release Script'
        run: |
          curl \
            --silent \
            --show-error \
            --output /tmp/release.sh \
            https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh

          chmod 700 /tmp/release.sh
      # Release Classic Addon on both CurseForge and WoWInterface
      - name: 'Release Classic Addon'
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          # -l Skip localisation replacements
          # -u Use Unix line-endings
          # -g Classic version
          /tmp/release.sh \
            -l \
            -u \
            -g 1.13.2
      # Release Retail Addon only on WoWInterface, as CurseForge is handled
      # elsewhere
      - name: 'Release Retail Addon'
        run: |
          # -d Skip upload
          # -l Skip localisation replacements
          # -u Use Unix line-endings
          /tmp/release.sh \
            -d \
            -l \
            -u
